//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Kiratech S.p.A.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoPermissionUser) DeepCopyInto(out *RepoPermissionUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoPermissionUser.
func (in *RepoPermissionUser) DeepCopy() *RepoPermissionUser {
	if in == nil {
		return nil
	}
	out := new(RepoPermissionUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoPermissionUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoPermissionUserList) DeepCopyInto(out *RepoPermissionUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepoPermissionUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoPermissionUserList.
func (in *RepoPermissionUserList) DeepCopy() *RepoPermissionUserList {
	if in == nil {
		return nil
	}
	out := new(RepoPermissionUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepoPermissionUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoPermissionUserParams) DeepCopyInto(out *RepoPermissionUserParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoPermissionUserParams.
func (in *RepoPermissionUserParams) DeepCopy() *RepoPermissionUserParams {
	if in == nil {
		return nil
	}
	out := new(RepoPermissionUserParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoPermissionUserSpec) DeepCopyInto(out *RepoPermissionUserSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoPermissionUserSpec.
func (in *RepoPermissionUserSpec) DeepCopy() *RepoPermissionUserSpec {
	if in == nil {
		return nil
	}
	out := new(RepoPermissionUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoPermissionUserStatus) DeepCopyInto(out *RepoPermissionUserStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoPermissionUserStatus.
func (in *RepoPermissionUserStatus) DeepCopy() *RepoPermissionUserStatus {
	if in == nil {
		return nil
	}
	out := new(RepoPermissionUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoPersmissionUserObservation) DeepCopyInto(out *RepoPersmissionUserObservation) {
	*out = *in
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.RepoSlug != nil {
		in, out := &in.RepoSlug, &out.RepoSlug
		*out = new(string)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
	if in.Permission != nil {
		in, out := &in.Permission, &out.Permission
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoPersmissionUserObservation.
func (in *RepoPersmissionUserObservation) DeepCopy() *RepoPersmissionUserObservation {
	if in == nil {
		return nil
	}
	out := new(RepoPersmissionUserObservation)
	in.DeepCopyInto(out)
	return out
}
