apiVersion: bitbucket.krateo.io/v1alpha1
kind: ProviderConfig
metadata:
  name: bitbucket-provider-config
spec:
  apiUrl: http://10.99.99.37:7990
  verbose: true
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: bitbucket-secret
      key: token